### ISSUE TITLE
Doesn't seem to support tuples in Haskell?

### ISSUE THREAD

**Issue by dorchard** [serras/patternr#1]
MWE:
`case (1, 2) of x -> ....`
Gives the the red ! mark.
Probably not too hard to add though!

**Comment by dorchard** [comment]
Sorry I just saw that this is not included in the support patterns! I guess this is a feature request then 
;)

**Comment by serras** [comment]
Actually, it was on my initial plans (the code for matching was there), but I forgot to write the parser. I'll try to deploy the new version tonight!
